### ISSUE TITLE
Quesstion on mTRL method 

### ISSUE THREAD

**Issue by queena12** [ZiadHatab/multiline-trl-calibration#2]
Hi ZiadHatab,
     I am wondering if we could use your alogrithm to get the error box's S-parameter, [Sleft] and [Sright]. The Equation is  [Sraw] = [Sleft][Sreal][Sright]

**Comment by ZiadHatab** [comment]
@queena12 

generally speaking, you cannot recover the left and right error boxes uniquely. The ambiguity comes from the fact that you are multiplying the matrices and you can always factor out a common scalar (we call this the 7th error term).

You can always obtain the S11 and S22 of both left and right error boxes uniquely. The problem is in the factor S12*S21. You need some method to separate them uniquely. One possible way, which is already part of my code, is to assume reciprocity of the error boxes, i.e., S21=S12. You can recover the reciprocal error boxes after calibration by running following code:
```python
cal.run_tug()   # perform the calibration
left_ntwk, right_ntwk = cal.receprical_ntwk() # return the error boxes under assumption of reciprocity
```

BTW, in applying the calibration we don't need to separate the error boxes, nor do we assume anything. It is just matrix inversion operation.
